id: homarr-labs/homarr
name: Homarr (homarr-labs)
description: "Homarr — tableau de bord moderne et personnalisable (image officielle homarr-labs)."
maintainers:
  - name: reptil3z0diak
    url: https://github.com/reptil3z0diak
icon: https://raw.githubusercontent.com/homarr-labs/homarr/main/public/img/homarr.png

compose:
  version: "3.8"
  services:
    homarr:
      image: ghcr.io/homarr-labs/homarr:latest
      container_name: homarr
      restart: unless-stopped
      ports:
        - "7575:7575"
      environment:
        - NODE_ENV=production
      volumes:
        - homarr_data:/app/data

volumes:
  homarr_data: {}
